#!/usr/bin/env node
// Generate src/types.ts, src/schemas.ts and src/agree.ts from schema.json.
//
// schema.json is the JSON Schema of everything that crosses the wasm boundary,
// printed by `cargo run -p linear-wasm --example schema`. This script handles
// exactly the subset of JSON Schema that schemars emits for those types and
// fails loudly on anything else, so a new kind of type is noticed rather than
// silently turned into `unknown`.
//
//   types.ts    the TypeScript types (no runtime code but SCHEMA_VERSION)
//   schemas.ts  zod schemas of the same types, and the values of every enum
//   agree.ts    compile-time proof that each zod schema and its type agree;
//               it is type-checked, never shipped
//
// None of them is committed: `npm run build` regenerates them from schema.json,
// which is.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

const doc = JSON.parse(readFileSync(here("schema.json"), "utf8"));
const defs = doc.$defs;
const operations = doc.operations;
const names = Object.keys(defs).sort();

const HEADER = `// Generated by scripts/generate.mjs from schema.json. Do not edit.\n`;

// ------------------------------------------------------------------ helpers

class Unsupported extends Error {}

function unsupported(schema, why) {
  return new Unsupported(`${why}: ${JSON.stringify(schema).slice(0, 200)}`);
}

function refName(ref) {
  const m = /^#\/\$defs\/(.+)$/.exec(ref);
  if (!m || !(m[1] in defs)) throw new Unsupported(`unresolvable $ref ${ref}`);
  return m[1];
}

const lower = (s) => s[0].toLowerCase() + s.slice(1);
const schemaConst = (name) => `${lower(name)}Schema`;
const valuesConst = (name, open) => `${lower(name)}${open ? "KnownValues" : "Values"}`;

const isOpenEnum = (s) =>
  s !== true && s.type === "string" && Array.isArray(s["x-known-values"]);

/**
 * The values of a closed string enum: `{ enum: [...] }`, or, when the variants
 * have doc comments, schemars' `{ oneOf: [{ const, description }, ...] }`.
 */
function enumValues(s) {
  if (s === true || s === false) return null;
  if (Array.isArray(s.enum) && s.type === "string") return s.enum;
  if (
    Array.isArray(s.oneOf) &&
    s.oneOf.length > 0 &&
    s.oneOf.every((m) => m !== true && typeof m.const === "string" && !m.properties)
  ) {
    return s.oneOf.map((m) => m.const);
  }
  return null;
}
const isStringEnum = (s) => enumValues(s) !== null;

function comment(description, pad) {
  if (!description) return "";
  const text = description.replaceAll("*/", "*\\/").trim();
  const lines = text.split("\n").map((l) => l.trimEnd());
  if (lines.length === 1) return `${pad}/** ${lines[0]} */\n`;
  return `${pad}/**\n${lines.map((l) => `${pad} * ${l}`.trimEnd()).join("\n")}\n${pad} */\n`;
}

const KNOWN_KEYWORDS = new Set([
  "$ref", "type", "format", "properties", "required", "additionalProperties", "items",
  "anyOf", "oneOf", "enum", "const", "description", "title", "default", "minimum",
  "maximum", "x-known-values", "$schema", "$defs",
]);

function checkKeywords(s) {
  for (const k of Object.keys(s)) {
    if (!KNOWN_KEYWORDS.has(k)) throw unsupported(s, `unsupported keyword ${k}`);
  }
}

const propKey = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

/** The schemas a schema is a union of, with `type: [..., "null"]` unfolded. */
function typesOf(s) {
  const types = Array.isArray(s.type) ? s.type : [s.type];
  if (types.some((t) => t === undefined)) throw unsupported(s, "schema without a type");
  return types;
}

function refsIn(s, into = new Set()) {
  if (s === true || s === false) return into;
  if (s.$ref) into.add(refName(s.$ref));
  for (const k of ["anyOf", "oneOf"]) for (const m of s[k] ?? []) refsIn(m, into);
  if (s.items) refsIn(s.items, into);
  for (const p of Object.values(s.properties ?? {})) refsIn(p, into);
  if (s.additionalProperties && typeof s.additionalProperties === "object") {
    refsIn(s.additionalProperties, into);
  }
  return into;
}

// -------------------------------------------------------------------- types

const indentOf = (n) => "  ".repeat(n);

function union(members, depth) {
  const flat = [...new Set(members.map((m) => m.text))];
  if (flat.length === 1) return flat[0];
  const multiline = members.some((m) => m.text.includes("\n") || m.doc) || flat.join(" | ").length > 80;
  if (!multiline) return flat.join(" | ");
  const pad = indentOf(depth + 1);
  return (
    "\n" +
    members
      .map((m) => `${m.doc ? comment(m.doc, pad) : ""}${pad}| ${m.text}`)
      .join("\n")
  );
}

/** `{ text, doc }` for a schema used as a member of a union. */
function member(s, depth) {
  return { text: tsType(s, depth + 1), doc: s !== true && s.description };
}

function tsType(s, depth = 0) {
  if (s === true) return "unknown";
  if (s === false) return "never";
  checkKeywords(s);
  if (s.$ref) return refName(s.$ref);
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (Array.isArray(s.enum)) return union(s.enum.map((v) => ({ text: JSON.stringify(v) })), depth);
  if (isOpenEnum(s)) {
    const known = s["x-known-values"].map((v) => ({ text: JSON.stringify(v) }));
    // `string & {}` keeps the editor offering the known values.
    return union([...known, { text: "(string & {})" }], depth);
  }
  if (s.anyOf || s.oneOf) {
    return union((s.anyOf ?? s.oneOf).map((m) => member(m, depth)), depth);
  }
  const parts = typesOf(s).map((t) => {
    switch (t) {
      case "string": return "string";
      case "integer": case "number": return "number";
      case "boolean": return "boolean";
      case "null": return "null";
      case "array": {
        const item = s.items === undefined ? "unknown" : tsType(s.items, depth);
        return /[|&]/.test(item) ? `(${item})[]` : `${item}[]`;
      }
      case "object": return tsObject(s, depth);
      default: throw unsupported(s, `unsupported type ${t}`);
    }
  });
  return union(parts.map((text) => ({ text })), depth);
}

function tsObject(s, depth) {
  const props = s.properties ?? {};
  const keys = Object.keys(props);
  if (keys.length === 0) {
    if (s.additionalProperties === false) return "Record<string, never>";
    if (s.additionalProperties && typeof s.additionalProperties === "object") {
      return `Record<string, ${tsType(s.additionalProperties, depth)}>`;
    }
    return "Record<string, unknown>";
  }
  const required = new Set(s.required ?? []);
  const pad = indentOf(depth + 1);
  const body = keys
    .map((k) => {
      const opt = required.has(k) ? "" : "?";
      return `${comment(props[k].description, pad)}${pad}${propKey(k)}${opt}: ${tsType(props[k], depth + 1)};`;
    })
    .join("\n");
  return `{\n${body}\n${indentOf(depth)}}`;
}

function emitTypes() {
  let out = HEADER;
  out += `\n/** The version of every JSON shape in this package. The wasm module reports the same number. */\n`;
  out += `export const SCHEMA_VERSION = ${doc.schemaVersion} as const;\n`;

  for (const name of names) {
    const s = defs[name];
    out += "\n" + comment(s.description, "");
    const isPlainObject =
      s.type === "object" && s.properties && Object.keys(s.properties).length > 0 && !s.anyOf;
    if (isPlainObject) {
      out += `export interface ${name} ${tsObject(s, 0)}\n`;
    } else {
      const t = tsType(s, 0);
      out += `export type ${name} =${t.startsWith("\n") ? "" : " "}${t};\n`;
    }
  }

  out += `\n/** Each operation \`build_request\` and \`parse_response\` know: its parameters and its result. */\n`;
  out += `export interface Operations {\n`;
  for (const [op, io] of Object.entries(operations)) {
    out += `  ${propKey(op)}: { params: ${tsType(io.params)}; data: ${tsType(io.data)} };\n`;
  }
  out += `}\n\nexport type OperationName = keyof Operations;\n`;
  return out;
}

// --------------------------------------------------------------------- zod

function zodString(s) {
  switch (s.format) {
    case undefined: return "z.string()";
    case "date-time": return "z.iso.datetime()";
    case "date": return "z.iso.date()";
    default: throw unsupported(s, `unsupported string format ${s.format}`);
  }
}

function zodType(s) {
  if (s === true) return "z.unknown()";
  if (s === false) return "z.never()";
  checkKeywords(s);
  if (s.$ref) return schemaConst(refName(s.$ref));
  if (s.const !== undefined) return `z.literal(${JSON.stringify(s.const)})`;
  if (isStringEnum(s)) return `z.enum(${JSON.stringify(enumValues(s))})`;
  if (isOpenEnum(s)) return "z.string()";
  if (s.anyOf || s.oneOf) {
    const alts = s.anyOf ?? s.oneOf;
    const nulls = alts.filter((a) => a !== true && a.type === "null");
    const rest = alts.filter((a) => !nulls.includes(a));
    if (nulls.length === 1 && rest.length === 1) return `${zodType(rest[0])}.nullable()`;
    const tag = s.oneOf ? discriminator(alts) : null;
    if (tag) return `z.discriminatedUnion(${JSON.stringify(tag)}, [${alts.map(zodType).join(", ")}])`;
    return `z.union([${alts.map(zodType).join(", ")}])`;
  }
  const types = typesOf(s);
  const nullable = types.includes("null");
  const rest = types.filter((t) => t !== "null");
  const one = (t) => {
    switch (t) {
      case "string": return zodString(s);
      case "integer": return `z.number().int()${s.minimum === 0 ? ".min(0)" : ""}`;
      case "number": return "z.number()";
      case "boolean": return "z.boolean()";
      case "array": return `z.array(${s.items === undefined ? "z.unknown()" : zodType(s.items)})`;
      case "object": return zodObject(s);
      default: throw unsupported(s, `unsupported type ${t}`);
    }
  };
  let out;
  if (rest.length === 0) out = "z.null()";
  else if (rest.length === 1) out = one(rest[0]);
  else out = `z.union([${rest.map(one).join(", ")}])`;
  return nullable && rest.length > 0 ? `${out}.nullable()` : out;
}

/** The property that tells the members of a `oneOf` apart, if there is one. */
function discriminator(alts) {
  const first = alts[0];
  if (first === true || !first.properties) return null;
  for (const key of Object.keys(first.properties)) {
    const consts = alts.map((a) => (a !== true && a.properties ? a.properties[key]?.const : undefined));
    if (consts.every((c) => c !== undefined) && new Set(consts).size === consts.length) return key;
  }
  return null;
}

function zodObject(s) {
  const props = s.properties ?? {};
  const keys = Object.keys(props);
  const ctor = s.additionalProperties === false ? "z.strictObject" : "z.object";
  if (keys.length === 0) {
    if (s.additionalProperties && typeof s.additionalProperties === "object") {
      return `z.record(z.string(), ${zodType(s.additionalProperties)})`;
    }
    return s.additionalProperties === false ? "z.strictObject({})" : "z.record(z.string(), z.unknown())";
  }
  const required = new Set(s.required ?? []);
  const fields = keys.map((k) => {
    const t = zodType(props[k]);
    return `  ${propKey(k)}: ${required.has(k) ? t : `${t}.optional()`},`;
  });
  return `${ctor}({\n${fields.join("\n")}\n})`;
}

/** Definitions in an order where each comes after the ones it refers to. */
function topological() {
  const order = [];
  const state = new Map();
  const visit = (name, path) => {
    if (state.get(name) === "done") return;
    if (state.get(name) === "active") {
      throw new Unsupported(`recursive type ${[...path, name].join(" -> ")}`);
    }
    state.set(name, "active");
    for (const dep of [...refsIn(defs[name])].sort()) visit(dep, [...path, name]);
    state.set(name, "done");
    order.push(name);
  };
  for (const name of names) visit(name, []);
  return order;
}

function emitSchemas() {
  let out = HEADER;
  out += `import { z } from "zod";\n`;

  for (const name of topological()) {
    const s = defs[name];
    out += "\n";
    if (isStringEnum(s) || isOpenEnum(s)) {
      const open = isOpenEnum(s);
      const values = open ? s["x-known-values"] : enumValues(s);
      out += comment(
        open
          ? `${s.description ?? name}\n\nThe values known today. Linear may add more, so the schema accepts any string.`
          : s.description,
        "",
      );
      out += `export const ${valuesConst(name, open)} = ${JSON.stringify(values)} as const;\n`;
      out += `export const ${schemaConst(name)} = ${open ? "z.string()" : `z.enum(${valuesConst(name, false)})`};\n`;
    } else {
      out += comment(s.description, "");
      out += `export const ${schemaConst(name)} = ${zodType(s)};\n`;
    }
  }

  out += `\n/** Each operation's parameters and result, for validating either at run time. */\n`;
  out += `export const operationSchemas = {\n`;
  for (const [op, io] of Object.entries(operations)) {
    out += `  ${propKey(op)}: { params: ${zodType(io.params)}, data: ${zodType(io.data)} },\n`;
  }
  out += `} as const;\n`;
  return out;
}

function emitAgree() {
  let out = HEADER;
  out += `\n// Each zod schema must describe exactly the type of the same name: assignable both ways.\n`;
  out += `import type { z } from "zod";\n`;
  out += `import type * as T from "./types.ts";\n`;
  out += `import type * as S from "./schemas.ts";\n`;
  out += `\ntype Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;\n`;
  out += `type Assert<X extends true> = X;\n\n`;
  for (const name of names) {
    out += `export type Agree${name} = Assert<Same<z.infer<typeof S.${schemaConst(name)}>, T.${name}>>;\n`;
  }
  return out;
}

// -------------------------------------------------------------------- write

mkdirSync(here("src"), { recursive: true });
const files = {
  "src/types.ts": emitTypes(),
  "src/schemas.ts": emitSchemas(),
  "src/agree.ts": emitAgree(),
};
for (const [path, text] of Object.entries(files)) {
  writeFileSync(here(path), text);
  console.log(`wrote ${path}`);
}
